data:
  end: '2023-01-01'
  split_date: '2019-01-01'
  start: '2010-01-01'
  ticker: ^GSPC
evaluation:
  eval_tickers:
  - ^GSPC
  - ^IXIC
  - ^GDAXI
  model_names:
  - xgb_trial_1
  - xgb_trial_2
  - xgb_trial_3
  - xgb_trial_4
  - xgb_trial_5
  pdf_report_name: chosen_features_report.pdf
features:
    - 10_day_rolling_volatility
    - 40_day_rolling_volatility
    - SMA_5
    - Momentumn5_20
    - 5_day_rolling_return
    - 10_day_rolling_return
    - 40_day_rolling_return
    - EWLR_0.8_1-20/20
    - lag_return_1/vol20
    - lag_return_3/vol20
    - lag_return_5/vol20
    - lag_return_6/vol20  
    - lag_return_10/vol20
    - lag_return_11/vol20
    - lag_return_14/vol20
    - Skew_20
    - Skew_40
    - Kurt_20
    - Kurt_40
    - Vol_momentum_5_40
    - Vol_momentum_10_20
    - Vol_momentum_20_40
    - Sharpe-like_5/20
    - Sharpe-like_10/20
    - Sharpe-like_20/40
    - Sharpe-like_40/VIX
    - log_returns_z_40
    - 5_day_rolling_vol_of_vol_5
    - 5_day_rolling_vol_of_vol_10
    - 5_day_rolling_vol_of_vol_20
    - 5_day_rolling_vol_of_vol_40
    - 10_day_rolling_vol_of_vol_5
    - 10_day_rolling_vol_of_vol_10
    - 10_day_rolling_vol_of_vol_20
    - 10_day_rolling_vol_of_vol_40
    - 20_day_rolling_vol_of_vol_5
    - 40_day_rolling_vol_of_vol_5
    - 40_day_rolling_vol_of_vol_40
    - VIX
    - 5_day_rolling_VIX
    - 5_day_rolling_vol_of_VIX
    - VIX_Momentumn5_10
    - VIX_Momentumn10_20
    - VIX_Momentumn10_40
    - lag_VIX_1
    - lag_VIX_6
    - lag_VIX_14
    - VIX_Skew_5
    - VIX_Skew_40
    - VIX_z_40
    - VIX/vol5
    - VIX/vol10
    - 5_day_rolling_VIX/vol20
    - 5_day_rolling_VIX/vol40
    - 40_day_rolling_VIX/vol40
    - 20_day_rolling_vol_of_VIX/vol5
    - 40_day_rolling_vol_of_VIX/vol10
    - 5_day_rolling_vol_of_VIX/vol40
    - 10_day_rolling_vol_of_VIX/vol40
    - VIX/vol10_Momentumn10_20
    - VIX/vol10_Momentumn10_40
    - VIX/vol20_Momentumn5_20
    - VIX/vol40_Momentumn5_10
    - VIX/vol40_Momentumn5_40
    - VIX/vol40_Momentumn10_20
    - lag_VIX/vol5_3
    - lag_VIX/vol5_5
    - lag_VIX/vol5_13
    - lag_VIX/vol5_19
    - lag_VIX/vol40_13
    - VIX/vol20_Skew_10
    - VIX/vol5_Kurt_20
    - VIX/vol10_Kurt_20
    - VIX/vol40_Kurt_10

training:
  early_stopping: 30
  model: xgb
  n_optuna_trials: 200
  top_n_models: 5
